import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import styles from '../styles/Home.module.css';
import { AiFillLinkedin, AiFillInstagram, AiFillGithub } from 'react-icons/ai';
import { FiCamera, FiEdit, FiBox } from 'react-icons/fi';
import design from '../public/BankApp.png';
import Api from '../public/MapApp.png';
import game from '../public/piggame.png';
import camera from '../public/camera.png';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nitin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">NitinSingh</h1>
            <ul className="flex items-center">
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                Home
              </li>
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                About
              </li>
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                Project
              </li>
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                <a href="#">Contact</a>
              </li>
            </ul>
          </nav>
        </section>
        <section className='lg:flex gap-10'>
          <div>
            <h3 className="text-3xl py-1">About</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I am a Developer and Photographer from India based in Toronto,
              Canada at Georgian Collage right now and continuing my education
              in computer programming I have learned many langugaes like swift,
              java, c++,c#,Javascript, mainframe I have learn full stack
              development with MERN/MEAN stack.
              <p className="text-md py-2 leading-8 texy-gray-800">
                I am learning new technologies day by day to improve my self
                daily basis. In my free time you can find me doing{' '}
                <a
                  href="https://www.pexels.com/@photographwithart/"
                  className="text-teal-500"
                >
                  Photography
                </a>
                , at the park doing exercise 🏋️‍♂️, at the beach for me time 🏖 or
                on photo walk and meetups in Toronto
              </p>
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={camera} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Photos
              </h3>
              <p className="py-2">
                Take the amazing shots from the camera doing the product
                Photography, Videography and taking it to the next level by
                editing
                <p className="py-4 text-teal-500">
                  Tools I use to edit the photos and Videos
                </p>
                <p className="text-gray-800 py-1">PhotoShop</p>
                <p className="text-gray-800 py-1">Lightroom</p>
                <p className="text-gray-800 py-1">Devinci Resolve</p>
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={camera} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design{' '}
              </h3>
              <p className="py-2">
                Take the amazing shots from the camera doing the product
                Photography, Videography and taking it to the next level by
                editing
                <p className="py-4 text-teal-500">
                  Tools I use to edit the photos and Videos
                </p>
                <p className="text-gray-800 py-1">PhotoShop</p>
                <p className="text-gray-800 py-1">Lightroom</p>
                <p className="text-gray-800 py-1">Devinci Resolve</p>
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={camera} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Website
              </h3>
              <p className="py-2">
                Take the amazing shots from the camera doing the product
                Photography, Videography and taking it to the next level by
                editing
                <p className="py-4 text-teal-500">
                  Tools I use to edit the photos and Videos
                </p>
                <p className="text-gray-800 py-1">PhotoShop</p>
                <p className="text-gray-800 py-1">Lightroom</p>
                <p className="text-gray-800 py-1">Devinci Resolve</p>
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3></h3>
          </div>
        </section>
      </main>
    </div>
  );
}
