import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import styles from '../styles/Home.module.css';
import { AiFillLinkedin, AiFillInstagram, AiFillGithub } from 'react-icons/ai';
import { FiCamera, FiEdit, FiBox } from 'react-icons/fi';
import design from '../public/BankApp.png';
import Api from '../public/MapApp.png';
import game from '../public/piggame.png';
import camera from '../public/camera.png';
import { useState } from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nitin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="  px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 pl-64 mb-12 rounded-md  items-center justify-between">
            <ul className="flex items-center">
              <li className="p-1 px-4 py-2 text-2xl font-medium  rounded-md ml-8">
                Home
              </li>
              <li className="p-1  px-4 py-2 text-2xl font-medium rounded-md ml-8">
                <a href="./aboutTemplate.js">About</a>
              </li>
              <li className="p-1  px-4 py-2 text-2xl font-medium rounded-md ml-8">
                <a href="./projectTemplate.js">Project</a>
              </li>
              <li className="p-1  px-4 py-2 text-2xl font-medium rounded-md ml-8">
                <a href="#">Contact</a>
              </li>
            </ul>
          </nav>
          <div className="relative mx-auto bg-gradient-to-b from-pale rounded-xl w-180 h-80 m-20 overflow-hidden md:h-96 md:w-196 text-center p-10">
            <h2 className="text-5xl text-darkpale font-medium md:text-6xl">
              Nitin Singh Chauhan
            </h2>
            <h3 className="text-2xl text-winter py-2 md:text-3xl">
              Developer, Designer and Photographer
            </h3>
            <p className="text-md py-5 leading-8 text-teal md:text-xl max-w-xl mx-auto">
              Freelancer providing services for programming needs like web
              developement and many more{' '}
              <a href="#" className="text-teal-500">
                Contact Me
              </a>
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-10 text-gray-600 m">
            <AiFillGithub />
            <AiFillInstagram />
            <AiFillLinkedin />
          </div>
          {/*  */}
        </section>
      </main>
    </div>
  );
}
