import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'
import {AiFillLinkedin, AiFilledIndeed} from 'react-icons'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nitin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl'>NitinSingh</h1>
          <ul className='flex items-center'>
            <li className='p-1'>
              Home
            </li>
            <li className='p-1'>About</li>
            <li className='p-1'>Project</li>
            <li className='p-1'><a href="#">Contact</a></li>
          </ul>
          </nav>
          <div className='text-center p-10'> 
            <h2 className='text-5xl text-teal-600 font-medium'>Nitin Singh Chauhan</h2>
            <h3 className='text-2xl py-2'>Developer, Designer and Photographer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Freelancer providing services for programming needs like web developement and many more <a href="#">Contact Me</a></p>
          </div>
        </section>
      </main>

   
    </div>
  )
}
