import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import styles from '../styles/Home.module.css';
import { AiFillLinkedin, AiFillInstagram, AiFillGithub } from 'react-icons/ai';
import { FiCamera, FiEdit, FiBox } from 'react-icons/fi';
import design from '../public/BankApp.png';
import Api from '../public/MapApp.png';
import game from '../public/piggame.png';
import camera from '../public/camera.png';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nitin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">NitinSingh</h1>
            <ul className="flex items-center">
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                Home
              </li>
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                About
              </li>
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                Project
              </li>
              <li className="p-1 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">
                <a href="#">Contact</a>
              </li>
            </ul>
          </nav>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Project</h3>
            <p className="text-md py-2 leading-8 text-gray-500">
              This is the project page for the portfolio website I will include
              projects in this page
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex">
            <div className="basis-1/3 flex-1">
              <Image
                src={design}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={game}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={Api}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={Api}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
